#!/bin/sh
#
# Creates a dkms.conf file

if [ "$1"="" ]; then
	PKG_NAME="$1"
else
	PKG_NAME="intel-platform-vsec-dkms"
fi

if [ "$2"="" ]; then
	PKG_VER="$2"
else
	PKG_VER="1.0"
fi

if [ "$3"="" ]; then
	REL_NAME="$3"
else
	REL_NAME="1"
fi

# We can label the here-doc lines for conditional output to the conf file
#
# Labels:
#  $ST: this line is added only when selftest is enabled
#
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME=$PKG_NAME
	PACKAGE_VERSION=$PKG_VER-$REL_NAME

	AUTOINSTALL="yes"

	BUILT_MODULE_NAME[0]="intel_vsec"
	BUILT_MODULE_LOCATION[0]="bin"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="pmt_class"
	BUILT_MODULE_LOCATION[1]="bin"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="pmt_telemetry"
	BUILT_MODULE_LOCATION[2]="bin"
	DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="pmt_crashlog"
	BUILT_MODULE_LOCATION[3]="bin"
	DEST_MODULE_LOCATION[3]="/updates"

	num_cpu_cores()
	{
	  if [ -x /usr/bin/nproc ]; then
	    nproc
	  else
	    echo "1"
	  fi
	}

	MAKE="'make' -j\$(num_cpu_cores) KDIR=/lib/modules/\$kernelver/build modules MODULE_VERSION=$PKG_VER-$REL_NAME; mkdir -p \$dkms_tree/$PKG_NAME/$PKG_VER-$REL_NAME/\$kernelver/x86_64/build/; cp drivers/platform/x86/intel/Module.symvers \$dkms_tree/$PKG_NAME/$PKG_VER-$REL_NAME/\$kernelver/x86_64/build/"
	CLEAN="'make' clean"
EOF
