#!/bin/sh
#
# Creates a dkms.conf file

if [ "$1"="" ]; then
	PKG_NAME="$1"
else
	PKG_NAME="intel-platform-pmt-dkms"
fi

if [ "$2"="" ]; then
	PKG_VER="$2"
else
	PKG_VER="1.0"
fi

if [ "$3"="" ]; then
	REL_NAME="$3"
else
	REL_NAME="1"
fi

# We can label the here-doc lines for conditional output to the conf file
#
# Labels:
#  $ST: this line is added only when selftest is enabled
#
sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
	PACKAGE_NAME=$PKG_NAME
	PACKAGE_VERSION=$PKG_VER-$REL_NAME
	REMAKE_INITRD="no"
	AUTOINSTALL="yes"

	BUILT_MODULE_NAME[0]="intel_pmt"
	BUILT_MODULE_LOCATION[0]="bin"
	DEST_MODULE_LOCATION[0]="/updates"

	BUILT_MODULE_NAME[1]="intel_pmt_class"
	BUILT_MODULE_LOCATION[1]="bin"
	DEST_MODULE_LOCATION[1]="/updates"

	BUILT_MODULE_NAME[2]="intel_pmt_telemetry"
	BUILT_MODULE_LOCATION[2]="bin"
	DEST_MODULE_LOCATION[2]="/updates"

	BUILT_MODULE_NAME[3]="intel_pmt_crashlog"
	BUILT_MODULE_LOCATION[3]="bin"
	DEST_MODULE_LOCATION[3]="/updates"

	num_cpu_cores()
	{
	  if [ -x /usr/bin/nproc ]; then
	    nproc
	  else
	    echo "1"
	  fi
	}

	MAKE="'make' -j\$(num_cpu_cores) KDIR=/lib/modules/\$kernelver/build"
	CLEAN="'make' clean"
EOF
